spring:
  main:
    allow-bean-definition-overriding: true
  data:
    mongodb:
      uri: mongodb://admin:admin@localhost:27017/lotto-web
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

lotto:
  number-generator:
    lotteryRunOccurrence: "*/7 * * * * *"
    facade:
      count: 25
      lowerBand: 1
      upperBand: 99
    http:
      client:
        config:
          uri: http://ec2-3-127-218-34.eu-central-1.compute.amazonaws.com
          port: 9090
          connectionTimeout: 5000
          readTimeout: 5000
  tickets-results:
    occurrence: "*/5 * * * * *"