spring:
  cache:
    type: redis
    redis:
      time-to-live: PT20M
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:63792}
    mongodb:
      uri: mongodb://admin:admin@localhost:27017/lotto-web
  main:
    allow-bean-definition-overriding: true
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

lotto:
  number-generator:
    lotteryRunOccurrence: "3 * * * * *"
#    lotteryRunOccurrence: "0 0 12 * * 6"
    facade:
      count: 25
      lowerBand: 1
      upperBand: 99
    http:
      client:
        config:
          uri: http://ec2-3-127-218-34.eu-central-1.compute.amazonaws.com
          port: 9090
          connectionTimeout: 5000
          readTimeout: 5000
  tickets-results:
    occurrence: "5 * * * * *"
#    occurrence: "00 55 11 * * 6"

auth:
  jwt:
    expirationDays: 30
    secret: ${JWT_SECRET}
    issuer: lotto-backend